<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>Assets/calculator-icon.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AdonisUI" Version="1.17.1" />
      <PackageReference Include="AdonisUI.ClassicTheme" Version="1.17.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Assets\calculator-icon.ico" />
      <Content Include="Assets\calculator-icon.ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
